server:
  port: 8830

eureka:
  # 显示服务IP地址
  instance:
      prefer-ip-address: true
  client:
    # 指定服务注册中心的位置
    service-url:
      defaultZone: http://localhost:8710/eureka/

spring:
  boot:
    admin:
      url: http://localhost:8720
      username: root
      password: 123456
      client:
        prefer-ip: true

# 是否需要秘钥认证
management:
  security:
    enabled: false

info:
  version: '@project.version@'





config:
  file:
    name: scis-warehousing-service-dev.yaml